//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dollar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportes
    {
        public int id_reporte { get; set; }
        public Nullable<int> clientes { get; set; }
        public Nullable<int> servicios { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual servicios servicios1 { get; set; }
    }
}
