insert tipo_servicio values('gastos')
insert tipo_servicio values('publicidad')
insert tipo_servicio values('Caja Chica')

---Insert de Tipo_Productos
insert into tipo_producto (descripcion) values ('Wine - Vovray Sec Domaine Huet');
insert into tipo_producto (descripcion) values ('Cucumber - Pickling Ontario');
insert into tipo_producto (descripcion) values ('Chocolate Bar - Smarties');
insert into tipo_producto (descripcion) values ('Basil - Dry, Rubbed');
insert into tipo_producto (descripcion) values ('Tomatoes - Cherry');
insert into tipo_producto (descripcion) values ('Pineapple - Canned, Rings');
insert into tipo_producto (descripcion) values ('Cucumber - Pickling Ontario');
insert into tipo_producto (descripcion) values ('Pepper - Roasted Red');
insert into tipo_producto (descripcion) values ('Cream - 18%');
insert into tipo_producto (descripcion) values ('Coffee Decaf Colombian');
insert into tipo_producto (descripcion) values ('Gatorade - Orange');
insert into tipo_producto (descripcion) values ('Chocolate Bar - Oh Henry');
insert into tipo_producto (descripcion) values ('Orange - Tangerine');
insert into tipo_producto (descripcion) values ('Higashimaru Usukuchi Soy');
insert into tipo_producto (descripcion) values ('Cheese - Woolwich Goat, Log');
insert into tipo_producto (descripcion) values ('Coffee - Decaffeinato Coffee');
insert into tipo_producto (descripcion) values ('Squid - Tubes / Tenticles 10/20');
insert into tipo_producto (descripcion) values ('Whmis Spray Bottle Graduated');
insert into tipo_producto (descripcion) values ('Temperature Recording Station');
insert into tipo_producto (descripcion) values ('Sprouts - Baby Pea Tendrils');
insert into tipo_producto (descripcion) values ('Milk - Skim');
insert into tipo_producto (descripcion) values ('Jameson - Irish Whiskey');
insert into tipo_producto (descripcion) values ('Pasta - Rotini, Colour, Dry');
insert into tipo_producto (descripcion) values ('Wonton Wrappers');
insert into tipo_producto (descripcion) values ('Sauce - Mint');
insert into tipo_producto (descripcion) values ('Wine - Magnotta - Belpaese');
insert into tipo_producto (descripcion) values ('Pie Shells 10');
insert into tipo_producto (descripcion) values ('Syrup - Monin - Passion Fruit');
insert into tipo_producto (descripcion) values ('Tarragon - Fresh');
insert into tipo_producto (descripcion) values ('Squash - Acorn');
insert into tipo_producto (descripcion) values ('Longos - Burritos');
insert into tipo_producto (descripcion) values ('Wine - Masi Valpolocell');
insert into tipo_producto (descripcion) values ('Puree - Mocha');
insert into tipo_producto (descripcion) values ('Coffee Cup 16oz Foam');
insert into tipo_producto (descripcion) values ('Potatoes - Pei 10 Oz');
insert into tipo_producto (descripcion) values ('Shopper Bag - S - 4');
insert into tipo_producto (descripcion) values ('Ham - Black Forest');
insert into tipo_producto (descripcion) values ('Tea - English Breakfast');
insert into tipo_producto (descripcion) values ('Tofu - Soft');
insert into tipo_producto (descripcion) values ('Cheese - Mozzarella');
insert into tipo_producto (descripcion) values ('Almonds Ground Blanched');
insert into tipo_producto (descripcion) values ('Olives - Morracan Dired');
insert into tipo_producto (descripcion) values ('Arctic Char - Fillets');
insert into tipo_producto (descripcion) values ('Pasta - Bauletti, Chicken White');
insert into tipo_producto (descripcion) values ('Pepper - Green, Chili');
insert into tipo_producto (descripcion) values ('Tea - Apple Green Tea');
insert into tipo_producto (descripcion) values ('Coffee Guatemala Dark');
insert into tipo_producto (descripcion) values ('Fish - Bones');
insert into tipo_producto (descripcion) values ('Coriander - Seed');
insert into tipo_producto (descripcion) values ('Pork - Ham Hocks - Smoked');
insert into tipo_producto (descripcion) values ('Cheese - Cheddar, Mild');
insert into tipo_producto (descripcion) values ('Duck - Whole');
insert into tipo_producto (descripcion) values ('Lemonade - Kiwi, 591 Ml');
insert into tipo_producto (descripcion) values ('Chicken - Wings, Tip Off');
insert into tipo_producto (descripcion) values ('Wine - Two Oceans Sauvignon');
insert into tipo_producto (descripcion) values ('Wine - Zinfandel Rosenblum');
insert into tipo_producto (descripcion) values ('Bagelers - Cinn / Brown');
insert into tipo_producto (descripcion) values ('Flower - Potmums');
insert into tipo_producto (descripcion) values ('Cheese - Le Cru Du Clocher');
insert into tipo_producto (descripcion) values ('Cheese - Parmesan Cubes');
insert into tipo_producto (descripcion) values ('Truffle - Peelings');
insert into tipo_producto (descripcion) values ('Sachet');
insert into tipo_producto (descripcion) values ('Longos - Lasagna Beef');
insert into tipo_producto (descripcion) values ('Sword Pick Asst');
insert into tipo_producto (descripcion) values ('Cheese - Blue');
insert into tipo_producto (descripcion) values ('Oil - Margarine');
insert into tipo_producto (descripcion) values ('Soda Water - Club Soda, 355 Ml');
insert into tipo_producto (descripcion) values ('Thermometer Digital');
insert into tipo_producto (descripcion) values ('Pasta - Fusili, Dry');
insert into tipo_producto (descripcion) values ('Wine - Chenin Blanc K.w.v.');
insert into tipo_producto (descripcion) values ('Cheese - Cheddar, Old White');
insert into tipo_producto (descripcion) values ('Salmon - Atlantic, No Skin');
insert into tipo_producto (descripcion) values ('Onions - White');
insert into tipo_producto (descripcion) values ('Eel Fresh');
insert into tipo_producto (descripcion) values ('Lime Cordial - Roses');
insert into tipo_producto (descripcion) values ('Muffin - Mix - Mango Sour Cherry');
insert into tipo_producto (descripcion) values ('Lettuce - Spring Mix');
insert into tipo_producto (descripcion) values ('Bread - Italian Corn Meal Poly');
insert into tipo_producto (descripcion) values ('Ice Cream - Life Savers');
insert into tipo_producto (descripcion) values ('Oil - Canola');
insert into tipo_producto (descripcion) values ('Tomatoes - Yellow Hot House');
insert into tipo_producto (descripcion) values ('Ham - Cooked Italian');
insert into tipo_producto (descripcion) values ('Zucchini - Mini, Green');
insert into tipo_producto (descripcion) values ('Carbonated Water - White Grape');
insert into tipo_producto (descripcion) values ('Paper - Brown Paper Mini Cups');
insert into tipo_producto (descripcion) values ('Crab - Soft Shell');
insert into tipo_producto (descripcion) values ('Salt And Pepper Mix - Black');
insert into tipo_producto (descripcion) values ('Ice Cream Bar - Drumstick');
insert into tipo_producto (descripcion) values ('Pear - Prickly');
insert into tipo_producto (descripcion) values ('Juice - V8, Tomato');
insert into tipo_producto (descripcion) values ('Pesto - Primerba, Paste');
insert into tipo_producto (descripcion) values ('Wine - White, Cooking');
insert into tipo_producto (descripcion) values ('Turkey - Whole, Fresh');
insert into tipo_producto (descripcion) values ('Appetizer - Smoked Salmon / Dill');
insert into tipo_producto (descripcion) values ('Muffin Mix - Corn Harvest');
insert into tipo_producto (descripcion) values ('Salmon - Smoked, Sliced');
insert into tipo_producto (descripcion) values ('Tea - Herbal Sweet Dreams');
insert into tipo_producto (descripcion) values ('Plate - Foam, Bread And Butter');
insert into tipo_producto (descripcion) values ('Figs');
insert into tipo_producto (descripcion) values ('Hersey Shakes');

--Insert se Productos
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Camembert', '$88.04', 55, 1);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Curry Powder Madras', '$53.03', 46, 2);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Oil - Shortening,liqud, Fry', '$83.94', 96, 3);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Crush - Grape, 355 Ml', '$59.41', 16, 4);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Spice - Montreal Steak Spice', '$32.33', 66, 5);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Redchard Merritt', '$91.23', 15, 6);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Schnappes - Peach, Walkers', '$73.65', 58, 7);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Turkey - Breast, Bone - In', '$36.83', 39, 8);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Oregano - Dry, Rubbed', '$88.15', 6, 9);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Ecolab - Medallion', '$61.51', 79, 10);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Romano, Grated', '$17.45', 85, 11);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Island Oasis - Magarita Mix', '$5.29', 72, 12);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Dasheen', '$58.07', 95, 13);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Red, Cooking', '$30.59', 69, 14);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Tea - Herbal I Love Lemon', '$32.53', 47, 15);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Guinea Fowl', '$74.26', 83, 16);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('White Fish - Filets', '$70.15', 69, 17);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Mushroom - Porcini, Dry', '$15.45', 88, 18);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pails With Lids', '$39.98', 39, 19);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Lentils - Green Le Puy', '$58.46', 51, 20);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Carbonated Water - Wildberry', '$86.33', 41, 21);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Seedlings - Mix, Organic', '$84.38', 49, 22);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Peach - Fresh', '$82.12', 99, 23);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Ham - Procutinni', '$49.48', 49, 24);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Tuna - Bluefin', '$33.75', 17, 25);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Scallops - Live In Shell', '$7.96', 35, 26);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Sugar - Splenda Sweetener', '$96.70', 15, 27);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Glaze - Clear', '$7.38', 50, 28);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Tea - Grapefruit Green Tea', '$96.16', 33, 29);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Victor Et Berthold', '$45.30', 6, 30);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Flour - Chickpea', '$91.51', 62, 31);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Asiago', '$18.23', 76, 32);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Feta', '$87.74', 59, 33);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pork - Ground', '$24.82', 95, 34);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Bread - Pita, Mini', '$8.18', 29, 35);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Filter - Coffee', '$17.86', 75, 36);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Island Oasis - Strawberry', '$76.10', 65, 37);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Mushroom - Oyster, Fresh', '$45.67', 15, 38);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Juice - Clamato, 341 Ml', '$51.77', 14, 39);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Huck Towels White', '$15.77', 63, 40);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Chick Peas - Dried', '$36.51', 43, 41);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Creme De Menth - White', '$13.03', 24, 42);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Carbonated Water - White Grape', '$13.32', 13, 43);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Veal - Round, Eye Of', '$76.03', 30, 44);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Contreau', '$12.74', 11, 45);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Corn - Mini', '$11.15', 63, 46);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Foam Dinner Plate', '$40.90', 60, 47);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pears - Anjou', '$63.76', 67, 48);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Soup - Campbells - Chicken Noodle', '$65.17', 51, 49);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Crab - Blue, Frozen', '$3.19', 41, 50);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Duck - Fat', '$85.06', 21, 51);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Doilies - 12, Paper', '$85.55', 67, 52);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Beef - Tenderloin - Aa', '$68.02', 19, 53);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Honey - Lavender', '$1.16', 14, 54);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Bay Leaf', '$97.21', 74, 55);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Mix', '$47.29', 76, 56);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Soup - Campbells, Beef Barley', '$82.41', 75, 57);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Lettuce - Belgian Endive', '$64.78', 10, 58);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Tomato Puree', '$67.09', 23, 59);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Bread - Bistro White', '$95.92', 53, 60);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Dill - Primerba, Paste', '$65.67', 92, 61);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cookie Dough - Peanut Butter', '$19.18', 14, 62);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('The Pop Shoppe - Lime Rickey', '$29.55', 66, 63);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Beef Cheek Fresh', '$95.96', 27, 64);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pea - Snow', '$5.79', 7, 65);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Quiche Assorted', '$26.63', 5, 66);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Cahors Ac 2000, Clos', '$71.39', 68, 67);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Fino Tio Pepe Gonzalez', '$89.17', 3, 68);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Skirt - 24 Foot', '$26.46', 79, 69);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Le Cheve Noir', '$74.92', 85, 70);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Bols Melon Liqueur', '$15.54', 33, 71);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Triple Sec - Mcguinness', '$22.88', 87, 72);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Beef - Tenderloin Tails', '$90.86', 18, 73);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cod - Black Whole Fillet', '$30.41', 55, 74);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Quiche Assorted', '$30.97', 64, 75);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Eggplant Italian', '$95.89', 72, 76);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Cheese - Wine', '$67.13', 70, 77);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Sea Urchin', '$90.56', 34, 78);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Scrubbie - Scotchbrite Hand Pad', '$58.23', 99, 79);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Curry Paste - Green Masala', '$67.38', 99, 80);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Papayas', '$77.25', 31, 81);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Spumante Bambino White', '$82.95', 21, 82);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pumpkin', '$80.10', 71, 83);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Nestea - Ice Tea, Diet', '$37.83', 19, 84);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Chips - Miss Vickies', '$29.51', 60, 85);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Lettuce - Treviso', '$59.25', 23, 86);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Radish - Black, Winter, Organic', '$61.70', 95, 87);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Catfish - Fillets', '$37.12', 20, 88);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Snapple - Iced Tea Peach', '$89.69', 16, 89);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Wine - Wyndham Estate Bin 777', '$35.67', 28, 90);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Hold Up Tool Storage Rack', '$70.54', 76, 91);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Veal - Knuckle', '$63.50', 89, 92);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Jameson Irish Whiskey', '$60.78', 12, 93);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Brocolinni - Gaylan, Chinese', '$11.56', 84, 94);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Milk - Skim', '$52.70', 81, 95);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Coffee - Espresso', '$47.97', 69, 96);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Bread Country Roll', '$94.11', 3, 97);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pasta - Orzo, Dry', '$98.82', 47, 98);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Milk - Skim', '$90.96', 27, 99);
insert into producto (nombre, precio, cantidad, tipo_producto) values ('Pate - Cognac', '$39.09', 58, 100);

--- Insert de continente
insert into continente (descripcion) values ('America');
insert into continente (descripcion) values ('Asia');
insert into continente (descripcion) values ('Europa');
insert into continente (descripcion) values ('Oceania');
insert into continente (descripcion) values ('Africa');

--- Insert Pais
insert into pais (descripcion) values ('Thailand');
insert into pais (descripcion) values ('Argentina');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('United States');
insert into pais (descripcion) values ('Greece');
insert into pais (descripcion) values ('United States');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Ukraine');
insert into pais (descripcion) values ('Brazil');
insert into pais (descripcion) values ('South Africa');
insert into pais (descripcion) values ('Mexico');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Russia');
insert into pais (descripcion) values ('Denmark');
insert into pais (descripcion) values ('Armenia');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Colombia');
insert into pais (descripcion) values ('Nicaragua');
insert into pais (descripcion) values ('Sweden');
insert into pais (descripcion) values ('Peru');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Mexico');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Sweden');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Russia');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Argentina');
insert into pais (descripcion) values ('Madagascar');
insert into pais (descripcion) values ('Colombia');
insert into pais (descripcion) values ('New Zealand');
insert into pais (descripcion) values ('Hungary');
insert into pais (descripcion) values ('Slovenia');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Bosnia and Herzegovina');
insert into pais (descripcion) values ('Lesotho');
insert into pais (descripcion) values ('Canada');
insert into pais (descripcion) values ('Puerto Rico');
insert into pais (descripcion) values ('Ukraine');
insert into pais (descripcion) values ('Greece');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Spain');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Finland');
insert into pais (descripcion) values ('Paraguay');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Ukraine');
insert into pais (descripcion) values ('Russia');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Bulgaria');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Serbia');
insert into pais (descripcion) values ('Japan');
insert into pais (descripcion) values ('Bangladesh');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Peru');
insert into pais (descripcion) values ('United States');
insert into pais (descripcion) values ('Iraq');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Peru');
insert into pais (descripcion) values ('Guatemala');
insert into pais (descripcion) values ('Nigeria');
insert into pais (descripcion) values ('Peru');
insert into pais (descripcion) values ('China');
insert into pais (descripcion) values ('Tanzania');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Japan');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Russia');
insert into pais (descripcion) values ('Japan');
insert into pais (descripcion) values ('Kosovo');
insert into pais (descripcion) values ('Macedonia');
insert into pais (descripcion) values ('Mexico');
insert into pais (descripcion) values ('Brazil');
insert into pais (descripcion) values ('Ukraine');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Japan');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Philippines');
insert into pais (descripcion) values ('Argentina');
insert into pais (descripcion) values ('Mongolia');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Poland');
insert into pais (descripcion) values ('Cuba');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Sweden');
insert into pais (descripcion) values ('Czech Republic');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Indonesia');
insert into pais (descripcion) values ('Tanzania');
insert into pais (descripcion) values ('Iran');
insert into pais (descripcion) values ('United States');
insert into pais (descripcion) values ('Ukraine');
insert into pais (descripcion) values ('Sweden');

--- insert Ciudad
insert into ciudad (descripcion) values ('Heishui');
insert into ciudad (descripcion) values ('Bella Vista');
insert into ciudad (descripcion) values ('Włosienica');
insert into ciudad (descripcion) values ('Lafayette');
insert into ciudad (descripcion) values ('Wuling');
insert into ciudad (descripcion) values ('Tranca');
insert into ciudad (descripcion) values ('Vänersborg');
insert into ciudad (descripcion) values ('Sison');
insert into ciudad (descripcion) values ('Kunwi');
insert into ciudad (descripcion) values ('Trélissac');
insert into ciudad (descripcion) values ('Wushan');
insert into ciudad (descripcion) values ('Gonghe');
insert into ciudad (descripcion) values ('Ciseuseupan');
insert into ciudad (descripcion) values ('Philadelphia');
insert into ciudad (descripcion) values ('Sobinka');
insert into ciudad (descripcion) values ('Ugbokpo');
insert into ciudad (descripcion) values ('Bali');
insert into ciudad (descripcion) values ('Baikouquan');
insert into ciudad (descripcion) values ('Březová');
insert into ciudad (descripcion) values ('Gorelki');
insert into ciudad (descripcion) values ('Batumi');
insert into ciudad (descripcion) values ('Santana do Ipanema');
insert into ciudad (descripcion) values ('Dongfeng');
insert into ciudad (descripcion) values ('Pangguang');
insert into ciudad (descripcion) values ('Zaranj');
insert into ciudad (descripcion) values ('Cernay');
insert into ciudad (descripcion) values ('Liangshui');
insert into ciudad (descripcion) values ('Gorbatov');
insert into ciudad (descripcion) values ('Grazhdanskoye');
insert into ciudad (descripcion) values ('Montréal-Ouest');
insert into ciudad (descripcion) values ('Pecka');
insert into ciudad (descripcion) values ('Suidong');
insert into ciudad (descripcion) values ('Lesnyye Polyany');
insert into ciudad (descripcion) values ('Karangboyo');
insert into ciudad (descripcion) values ('Aleshtar');
insert into ciudad (descripcion) values ('Aikmel');
insert into ciudad (descripcion) values ('Douz');
insert into ciudad (descripcion) values ('Amga');
insert into ciudad (descripcion) values ('Pulosari');
insert into ciudad (descripcion) values ('Isyangulovo');
insert into ciudad (descripcion) values ('Tambakromo');
insert into ciudad (descripcion) values ('Rongkou');
insert into ciudad (descripcion) values ('Al Manqaf');
insert into ciudad (descripcion) values ('Khon Buri');
insert into ciudad (descripcion) values ('Bom Jesus do Itabapoana');
insert into ciudad (descripcion) values ('Quimper');
insert into ciudad (descripcion) values ('Walenrang');
insert into ciudad (descripcion) values ('Phultala');
insert into ciudad (descripcion) values ('Wadi Kidul');
insert into ciudad (descripcion) values ('Ban Pong');
insert into ciudad (descripcion) values ('Horodne');
insert into ciudad (descripcion) values ('Rio Formoso');
insert into ciudad (descripcion) values ('Nizhyn');
insert into ciudad (descripcion) values ('Seixo de Manhoses');
insert into ciudad (descripcion) values ('Checacupe');
insert into ciudad (descripcion) values ('Cambuga');
insert into ciudad (descripcion) values ('Velykyy Burluk');
insert into ciudad (descripcion) values ('København');
insert into ciudad (descripcion) values ('Sungaikakap');
insert into ciudad (descripcion) values ('Novo');
insert into ciudad (descripcion) values ('Dofa');
insert into ciudad (descripcion) values ('Visim');
insert into ciudad (descripcion) values ('Harding');
insert into ciudad (descripcion) values ('Bollène');
insert into ciudad (descripcion) values ('Yarīm');
insert into ciudad (descripcion) values ('Kiamba');
insert into ciudad (descripcion) values ('Libao');
insert into ciudad (descripcion) values ('Hamburg Harvestehude');
insert into ciudad (descripcion) values ('Qiaoxia');
insert into ciudad (descripcion) values ('Borås');
insert into ciudad (descripcion) values ('Trstenik');
insert into ciudad (descripcion) values ('Fenjie');
insert into ciudad (descripcion) values ('Ḩawf');
insert into ciudad (descripcion) values ('Pimenta Bueno');
insert into ciudad (descripcion) values ('Baní');
insert into ciudad (descripcion) values ('Rasskazovo');
insert into ciudad (descripcion) values ('Xiaoshiqiao');
insert into ciudad (descripcion) values ('Dadian');
insert into ciudad (descripcion) values ('Kiszkowo');
insert into ciudad (descripcion) values ('Novopskov');
insert into ciudad (descripcion) values ('Donggong');
insert into ciudad (descripcion) values ('Karabas');
insert into ciudad (descripcion) values ('Rudniki');
insert into ciudad (descripcion) values ('Ghayl Bā Wazīr');
insert into ciudad (descripcion) values ('Omišalj');
insert into ciudad (descripcion) values ('Sakharovo');
insert into ciudad (descripcion) values ('Iwatsuki');
insert into ciudad (descripcion) values ('Chenqiao');
insert into ciudad (descripcion) values ('Vårby');
insert into ciudad (descripcion) values ('Sandaohezi');
insert into ciudad (descripcion) values ('Luhe');
insert into ciudad (descripcion) values ('Bourgoin-Jallieu');
insert into ciudad (descripcion) values ('Staryy Oskol');
insert into ciudad (descripcion) values ('Jinan-gun');
insert into ciudad (descripcion) values ('Trinidad');
insert into ciudad (descripcion) values ('Quito');
insert into ciudad (descripcion) values ('Gengzhuang');
insert into ciudad (descripcion) values ('Mburukullu');
insert into ciudad (descripcion) values ('Aheloy');
insert into ciudad (descripcion) values ('Maroantsetra');

--- Insert Ubicacion
insert into ubicacion (continente, pais, ciudad) values (1, 48, 24);
insert into ubicacion (continente, pais, ciudad) values (2, 52, 36);
insert into ubicacion (continente, pais, ciudad) values (2, 47, 40);
insert into ubicacion (continente, pais, ciudad) values (4, 65, 1);
insert into ubicacion (continente, pais, ciudad) values (1, 52, 10);
insert into ubicacion (continente, pais, ciudad) values (3, 56, 23);
insert into ubicacion (continente, pais, ciudad) values (4, 23, 90);
insert into ubicacion (continente, pais, ciudad) values (3, 84, 22);
insert into ubicacion (continente, pais, ciudad) values (5, 80, 5);
insert into ubicacion (continente, pais, ciudad) values (1, 4, 12);
insert into ubicacion (continente, pais, ciudad) values (4, 27, 71);
insert into ubicacion (continente, pais, ciudad) values (3, 17, 21);
insert into ubicacion (continente, pais, ciudad) values (3, 53, 16);
insert into ubicacion (continente, pais, ciudad) values (4, 22, 8);
insert into ubicacion (continente, pais, ciudad) values (4, 43, 74);
insert into ubicacion (continente, pais, ciudad) values (4, 7, 67);
insert into ubicacion (continente, pais, ciudad) values (2, 14, 30);
insert into ubicacion (continente, pais, ciudad) values (3, 2, 10);
insert into ubicacion (continente, pais, ciudad) values (4, 19, 73);
insert into ubicacion (continente, pais, ciudad) values (2, 36, 34);
insert into ubicacion (continente, pais, ciudad) values (2, 88, 94);
insert into ubicacion (continente, pais, ciudad) values (4, 11, 89);
insert into ubicacion (continente, pais, ciudad) values (3, 79, 67);
insert into ubicacion (continente, pais, ciudad) values (5, 3, 60);
insert into ubicacion (continente, pais, ciudad) values (1, 95, 36);
insert into ubicacion (continente, pais, ciudad) values (1, 9, 3);
insert into ubicacion (continente, pais, ciudad) values (1, 16, 32);
insert into ubicacion (continente, pais, ciudad) values (4, 93, 83);
insert into ubicacion (continente, pais, ciudad) values (5, 20, 15);
insert into ubicacion (continente, pais, ciudad) values (5, 83, 6);
insert into ubicacion (continente, pais, ciudad) values (3, 62, 9);
insert into ubicacion (continente, pais, ciudad) values (3, 26, 13);
insert into ubicacion (continente, pais, ciudad) values (2, 15, 37);
insert into ubicacion (continente, pais, ciudad) values (1, 27, 28);
insert into ubicacion (continente, pais, ciudad) values (4, 7, 75);
insert into ubicacion (continente, pais, ciudad) values (2, 15, 84);
insert into ubicacion (continente, pais, ciudad) values (4, 56, 82);
insert into ubicacion (continente, pais, ciudad) values (4, 16, 50);
insert into ubicacion (continente, pais, ciudad) values (3, 62, 81);
insert into ubicacion (continente, pais, ciudad) values (1, 57, 85);
insert into ubicacion (continente, pais, ciudad) values (3, 15, 56);
insert into ubicacion (continente, pais, ciudad) values (2, 94, 3);
insert into ubicacion (continente, pais, ciudad) values (3, 80, 48);
insert into ubicacion (continente, pais, ciudad) values (4, 91, 64);
insert into ubicacion (continente, pais, ciudad) values (2, 89, 92);
insert into ubicacion (continente, pais, ciudad) values (2, 52, 6);
insert into ubicacion (continente, pais, ciudad) values (1, 2, 31);
insert into ubicacion (continente, pais, ciudad) values (5, 78, 82);
insert into ubicacion (continente, pais, ciudad) values (1, 22, 3);
insert into ubicacion (continente, pais, ciudad) values (3, 24, 47);
insert into ubicacion (continente, pais, ciudad) values (2, 5, 45);
insert into ubicacion (continente, pais, ciudad) values (2, 37, 46);
insert into ubicacion (continente, pais, ciudad) values (1, 1, 59);
insert into ubicacion (continente, pais, ciudad) values (1, 17, 91);
insert into ubicacion (continente, pais, ciudad) values (3, 94, 95);
insert into ubicacion (continente, pais, ciudad) values (1, 54, 69);
insert into ubicacion (continente, pais, ciudad) values (5, 26, 17);
insert into ubicacion (continente, pais, ciudad) values (4, 54, 54);
insert into ubicacion (continente, pais, ciudad) values (3, 16, 50);
insert into ubicacion (continente, pais, ciudad) values (2, 78, 90);
insert into ubicacion (continente, pais, ciudad) values (4, 42, 71);
insert into ubicacion (continente, pais, ciudad) values (4, 27, 10);
insert into ubicacion (continente, pais, ciudad) values (5, 5, 5);
insert into ubicacion (continente, pais, ciudad) values (1, 95, 6);
insert into ubicacion (continente, pais, ciudad) values (4, 29, 1);
insert into ubicacion (continente, pais, ciudad) values (1, 57, 26);
insert into ubicacion (continente, pais, ciudad) values (1, 92, 100);
insert into ubicacion (continente, pais, ciudad) values (3, 61, 65);
insert into ubicacion (continente, pais, ciudad) values (1, 15, 1);
insert into ubicacion (continente, pais, ciudad) values (1, 41, 17);
insert into ubicacion (continente, pais, ciudad) values (4, 28, 91);
insert into ubicacion (continente, pais, ciudad) values (5, 32, 60);
insert into ubicacion (continente, pais, ciudad) values (4, 63, 58);
insert into ubicacion (continente, pais, ciudad) values (4, 37, 20);
insert into ubicacion (continente, pais, ciudad) values (4, 76, 36);
insert into ubicacion (continente, pais, ciudad) values (3, 51, 37);
insert into ubicacion (continente, pais, ciudad) values (1, 55, 62);
insert into ubicacion (continente, pais, ciudad) values (1, 94, 1);
insert into ubicacion (continente, pais, ciudad) values (3, 21, 71);
insert into ubicacion (continente, pais, ciudad) values (4, 74, 91);
insert into ubicacion (continente, pais, ciudad) values (1, 53, 82);
insert into ubicacion (continente, pais, ciudad) values (4, 73, 19);
insert into ubicacion (continente, pais, ciudad) values (4, 20, 67);
insert into ubicacion (continente, pais, ciudad) values (5, 100, 60);
insert into ubicacion (continente, pais, ciudad) values (3, 42, 63);
insert into ubicacion (continente, pais, ciudad) values (5, 63, 77);
insert into ubicacion (continente, pais, ciudad) values (5, 71, 2);
insert into ubicacion (continente, pais, ciudad) values (5, 16, 93);
insert into ubicacion (continente, pais, ciudad) values (4, 33, 16);
insert into ubicacion (continente, pais, ciudad) values (3, 21, 92);
insert into ubicacion (continente, pais, ciudad) values (1, 100, 53);
insert into ubicacion (continente, pais, ciudad) values (2, 22, 32);
insert into ubicacion (continente, pais, ciudad) values (4, 14, 92);
insert into ubicacion (continente, pais, ciudad) values (4, 56, 66);
insert into ubicacion (continente, pais, ciudad) values (5, 63, 74);
insert into ubicacion (continente, pais, ciudad) values (2, 35, 38);
insert into ubicacion (continente, pais, ciudad) values (4, 1, 87);
insert into ubicacion (continente, pais, ciudad) values (2, 20, 63);
insert into ubicacion (continente, pais, ciudad) values (4, 83, 35);
insert into ubicacion (continente, pais, ciudad) values (3, 86, 65);

---insert servicios
insert into servicios  (tipo_servicio, porcentaje) values ('Gastas',5);
insert into servicios  (tipo_servicio, porcentaje) values ('Publicidad',10);
insert into servicios  (tipo_servicio, porcentaje) values ('Caja Chica',85);

---Inser cliente
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Graig', 'Butterley', '239-623-9181', 74, 174);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Wood', 'Goathrop', '615-953-2911', 8, 132);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Honor', 'Ripsher', '688-409-1416', 71, 158);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Lee', 'Langmuir', '477-605-8059', 71, 176);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Nydia', 'Hassen', '871-881-3157', 22, 126);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Mab', 'Waylen', '293-911-4219', 5, 129);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Cornelle', 'Dollard', '899-832-4347', 75, 144);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Bat', 'Mulloch', '744-832-2230', 13, 122);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Charlene', 'Ferrier', '404-969-1173', 40, 180);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Erica', 'Glanert', '997-851-8855', 58, 101);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Benedict', 'Keemar', '369-569-9822', 39, 192);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Terrye', 'Wainwright', '337-264-6235', 20, 182);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Perceval', 'Allsopp', '975-231-4605', 71, 161);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Urbanus', 'Dellar', '953-151-8033', 30, 133);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Henrieta', 'Donaldson', '734-441-1511', 26, 145);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Hank', 'Gammage', '840-538-4427', 22, 150);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Siegfried', 'Ianni', '468-777-9742', 82, 195);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Magdalen', 'Bunton', '398-671-7843', 34, 113);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Bastian', 'Penchen', '361-695-0965', 34, 166);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Leif', 'Di Angelo', '540-272-4665', 47, 124);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Carlita', 'Inkpen', '313-677-5471', 59, 119);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Clyve', 'Du Fray', '747-343-9802', 72, 106);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Tymothy', 'Kynastone', '121-426-1812', 41, 160);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Chaim', 'Gillham', '215-254-5587', 75, 119);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Tanya', 'Pering', '491-424-2729', 53, 105);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Kristan', 'Catto', '569-838-1698', 89, 143);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Martino', 'Sprowles', '751-786-4018', 15, 102);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Gerald', 'Inker', '325-110-5703', 37, 179);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Davy', 'Minger', '559-155-7359', 80, 195);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Lanita', 'Perutto', '333-328-7510', 63, 178);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Lucita', 'Paylor', '201-303-2136', 32, 102);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Theresita', 'Hinchcliffe', '300-621-8512', 3, 200);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Burke', 'Tampen', '589-698-8857', 75, 154);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Garwood', 'Beedom', '551-678-0225', 56, 187);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Berni', 'Offill', '577-905-4207', 68, 172);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Lind', 'Seagar', '780-802-7390', 52, 117);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Theodor', 'Copsey', '918-528-7139', 48, 129);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Carlynne', 'Harfoot', '348-839-3666', 26, 180);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Jan', 'Kibby', '377-500-5795', 77, 105);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Reinold', 'Deluce', '145-126-0094', 97, 131);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Michele', 'Spyvye', '903-775-9370', 50, 170);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Juana', 'Commuzzo', '116-159-4283', 22, 177);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Sibel', 'Deveral', '345-863-6461', 80, 136);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Lynn', 'McLanachan', '657-627-2197', 69, 135);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Kelcie', 'Bedenham', '519-684-6462', 84, 186);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Merv', 'Nicol', '607-850-5962', 20, 169);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Rockwell', 'Stubbings', '829-900-1290', 99, 111);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Dorine', 'Castrillo', '145-950-1113', 41, 151);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Michail', 'Nutman', '740-235-7726', 92, 126);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Costanza', 'Bayliss', '764-941-7733', 20, 182);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Charlotta', 'Vaudrey', '477-792-3871', 80, 190);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Jerrie', 'Detoile', '479-378-7019', 26, 138);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Talyah', 'Ruslen', '597-745-0773', 33, 137);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Tybie', 'Lampett', '257-572-6080', 17, 131);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Sunny', 'Yarnton', '904-659-7546', 75, 136);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Adi', 'Faherty', '489-910-5015', 38, 110);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Celka', 'Ryton', '325-685-9450', 75, 190);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Thatcher', 'Corzor', '128-675-9660', 46, 170);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Daloris', 'Aked', '915-864-6490', 39, 164);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Caty', 'Offill', '622-896-3634', 51, 187);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Kenny', 'Howford', '632-692-8054', 67, 190);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Sasha', 'Narducci', '759-940-2519', 90, 157);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Robers', 'Bough', '198-796-2072', 49, 139);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('El', 'Gilks', '475-169-3877', 22, 139);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Daveen', 'Skehan', '938-120-7062', 43, 125);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Chevalier', 'Josipovic', '524-593-2970', 8, 127);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Miran', 'McLenahan', '351-461-7119', 49, 193);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Duke', 'Ferre', '983-891-1959', 71, 170);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Hoyt', 'Duling', '196-750-6584', 74, 171);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Meta', 'Spedding', '703-645-1262', 69, 166);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Standford', 'Poli', '196-199-4350', 71, 147);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Cyrill', 'Topham', '588-109-8669', 4, 121);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Ondrea', 'Hazard', '238-805-4679', 43, 110);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Neil', 'Stranahan', '714-507-3164', 32, 120);
insert into cliente (nombre, apellido, telefono, producto, ubicacion) values ('Pate', 'Curnow', '439-131-6746', 36, 124);

--- insert Reportes

insert into reportes (clientes, servicios) values (131, 359);
insert into reportes (clientes, servicios) values (173, 359);
insert into reportes (clientes, servicios) values (136, 360);
insert into reportes (clientes, servicios) values (169, 359);
insert into reportes (clientes, servicios) values (176, 359);
insert into reportes (clientes, servicios) values (130, 358);
insert into reportes (clientes, servicios) values (134, 358);
insert into reportes (clientes, servicios) values (124, 360);
insert into reportes (clientes, servicios) values (145, 360);
insert into reportes (clientes, servicios) values (111, 360);
insert into reportes (clientes, servicios) values (145, 360);
insert into reportes (clientes, servicios) values (105, 360);
insert into reportes (clientes, servicios) values (165, 358);
insert into reportes (clientes, servicios) values (128, 359);
insert into reportes (clientes, servicios) values (129, 359);
insert into reportes (clientes, servicios) values (116, 359);
insert into reportes (clientes, servicios) values (167, 358);
insert into reportes (clientes, servicios) values (164, 358);
insert into reportes (clientes, servicios) values (150, 358);
insert into reportes (clientes, servicios) values (150, 360);
insert into reportes (clientes, servicios) values (147, 360);
insert into reportes (clientes, servicios) values (152, 360);
insert into reportes (clientes, servicios) values (137, 360);
insert into reportes (clientes, servicios) values (144, 360);
insert into reportes (clientes, servicios) values (121, 359);
insert into reportes (clientes, servicios) values (108, 359);
insert into reportes (clientes, servicios) values (122, 359);
insert into reportes (clientes, servicios) values (157, 360);
insert into reportes (clientes, servicios) values (158, 360);
insert into reportes (clientes, servicios) values (107, 360);
insert into reportes (clientes, servicios) values (125, 359);
insert into reportes (clientes, servicios) values (144, 359);
insert into reportes (clientes, servicios) values (128, 358);
insert into reportes (clientes, servicios) values (128, 359);
insert into reportes (clientes, servicios) values (159, 360);
insert into reportes (clientes, servicios) values (106, 359);
insert into reportes (clientes, servicios) values (114, 360);
insert into reportes (clientes, servicios) values (143, 359);
insert into reportes (clientes, servicios) values (154, 358);
insert into reportes (clientes, servicios) values (138, 359);
insert into reportes (clientes, servicios) values (174, 359);
insert into reportes (clientes, servicios) values (162, 358);
insert into reportes (clientes, servicios) values (117, 359);
insert into reportes (clientes, servicios) values (128, 360);
insert into reportes (clientes, servicios) values (162, 358);
insert into reportes (clientes, servicios) values (133, 360);
insert into reportes (clientes, servicios) values (130, 358);
insert into reportes (clientes, servicios) values (145, 360);
insert into reportes (clientes, servicios) values (109, 358);
insert into reportes (clientes, servicios) values (124, 359);
insert into reportes (clientes, servicios) values (135, 358);
insert into reportes (clientes, servicios) values (132, 359);
insert into reportes (clientes, servicios) values (133, 358);
insert into reportes (clientes, servicios) values (122, 360);
insert into reportes (clientes, servicios) values (175, 359);
insert into reportes (clientes, servicios) values (110, 359);
insert into reportes (clientes, servicios) values (140, 359);
insert into reportes (clientes, servicios) values (120, 360);
insert into reportes (clientes, servicios) values (145, 359);
insert into reportes (clientes, servicios) values (151, 358);
insert into reportes (clientes, servicios) values (112, 359);
insert into reportes (clientes, servicios) values (113, 360);
insert into reportes (clientes, servicios) values (132, 359);
insert into reportes (clientes, servicios) values (124, 359);
insert into reportes (clientes, servicios) values (156, 358);
insert into reportes (clientes, servicios) values (112, 360);
insert into reportes (clientes, servicios) values (154, 360);
insert into reportes (clientes, servicios) values (135, 359);
insert into reportes (clientes, servicios) values (146, 360);
insert into reportes (clientes, servicios) values (107, 360);
insert into reportes (clientes, servicios) values (151, 359);
insert into reportes (clientes, servicios) values (150, 358);
insert into reportes (clientes, servicios) values (103, 358);
insert into reportes (clientes, servicios) values (131, 360);
insert into reportes (clientes, servicios) values (159, 358);
